name: HTTP Request Action

on:
  push:
    branches: [develop]

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          SCORE=$(echo ${{ github.event.head_commit.author.message }} | cut -d '|' -f 2)
          USER=${{ github.event.head_commit.author.username }}
          echo $SCORE,$USER

          curl --data "user=$USER&score=100" --request POST https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/

#     - name: Deploy Stage
#       uses: fjogeleit/http-request-action@master
#       with:
#         url: 'https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/' # use the server url here
#         method: 'POST'
#         data: '{ "user":  "${{ github.event.pull_request.user.login }}" , "score": "${{ github.event.label.name }}" }'

